name: Firebase Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'functions/**'  # functionsディレクトリの変更時のみ実行

jobs:
  deploy:
    name: Deploy Firebase Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          # キャッシュは無効化
          # cache: 'npm'
          # cache-dependency-path: './functions/package-lock.json'

      # ルートディレクトリでもnpm installを実行（既存のpackage.jsonを使用）
      - name: Install root dependencies
        run: npm install --no-package-lock

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies in functions directory
        working-directory: ./functions
        run: npm ci

      # 型定義ファイルをインストールするステップを追加
      - name: Install TypeScript type definitions
        working-directory: ./functions
        run: |
          npm install --save-dev @types/node
          npm install --save-dev @types/dotenv
          npm install --save-dev @types/axios

      - name: Show source code for debugging
        working-directory: ./functions
        run: |
          echo "Content of index.ts file:"
          cat src/index.ts
          echo "-----------------------------------"

      - name: Create .env file
        working-directory: ./functions
        run: |
          echo "LINE_ACCESS_TOKEN=${{ secrets.LINE_ACCESS_TOKEN }}" > .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "BOT_USER_ID=${{ secrets.BOT_USER_ID }}" >> .env

      # ビルド前にTypeScriptコンパイラがモジュールを見つけられるようにTSConfigを確認
      - name: Check TypeScript configuration
        working-directory: ./functions
        run: |
          echo "Checking tsconfig.json"
          cat tsconfig.json
          echo "Installing additional types if needed"
          npm list firebase-functions || npm install firebase-functions
          npm list axios || npm install axios
          npm list dotenv || npm install dotenv

      - name: Verbose build
        working-directory: ./functions
        run: npx tsc --traceResolution

      - name: Deploy to Firebase
        run: firebase deploy --only functions:lineTranslateBot --project translate-kkz --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive 