name: Firebase Deploy

on:
  push:
    branches: [ main ]
    paths:
     - 'functions/**'  # functionsディレクトリの変更時のみ実行

jobs:
  deploy:
    name: Deploy Firebase Functions
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 依存関係をインストール
      - name: Install Dependencies
        run: npm install

      # Firebase CLIをインストール（グローバルインストールなのでworking-directoryを上書き）
      - name: Install Firebase CLI
        working-directory: .
        run: npm install -g firebase-tools

      # 必要なディレクトリとファイルを作成
      - name: Create necessary directories and files
        run: |
          mkdir -p src/types
          cat > src/types/types.d.ts << 'EOL'
          declare module "axios";
          declare module "dotenv";
          declare module "firebase-functions/v2/https" {
            export function onRequest(
              handler: (request: any, response: any) => void | Promise<void>
            ): any;
          }
          declare module "firebase-functions/logger" {
            export function info(message: string, data?: any): void;
            export function error(message: string, error?: any): void;
          }
          declare namespace NodeJS {
            interface Process {
              env: {
                [key: string]: string | undefined;
                LINE_ACCESS_TOKEN?: string;
                OPENAI_API_KEY?: string;
                BOT_USER_ID?: string;
              }
            }
          }
          EOL

      # 環境変数を設定
      - name: Create .env file
        run: |
          echo "LINE_ACCESS_TOKEN=${{ secrets.LINE_ACCESS_TOKEN }}" > .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "BOT_USER_ID=${{ secrets.BOT_USER_ID }}" >> .env

      # ビルドを実行
      - name: Build
        run: npm run build

      # Lintチェックを実行
      - name: Lint
        run: npm run lint

      # Firebaseにデプロイ
      - name: Deploy to Firebase
        working-directory: .
        run: firebase deploy --only functions:lineTranslateBot --project translate-kkz --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive  --force 