name: Firebase Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'functions/**'  # functionsディレクトリの変更時のみ実行

jobs:
  deploy:
    name: Deploy Firebase Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Node 18を使用

      # ルートディレクトリの依存関係をインストール
      - name: Install Dependencies
        run: npm install

      # functionsディレクトリの依存関係をインストール
      - name: Install Functions Dependencies
        run: cd functions && npm install

      # Firebase CLIをインストール
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 環境変数を設定
      - name: Create .env file
        working-directory: ./functions
        run: |
          echo "LINE_ACCESS_TOKEN=${{ secrets.LINE_ACCESS_TOKEN }}" > .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "BOT_USER_ID=${{ secrets.BOT_USER_ID }}" >> .env

      # ビルドを実行
      - name: Build
        run: npm run build

      # Firebaseにデプロイ
      - name: Deploy to Firebase
        run: firebase deploy --only functions:lineTranslateBot --project translate-kkz --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive 